backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;


use yii\web\Controller;
use frontend\models\User;
use yii\web\Cookie;
use GeoIp2\Database\Reader;
use yii\base\ErrorException;

use frontend\models\UploadedForm;
use yii\web\UploadedFile;
use yii\web\Response;
use Yii;
//use yii\web\Session;
//use frontend\modules\post\models\Feed;

/**
 * Site controller
 */
class SiteController extends Controller
{
    
   
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

//    public function behaviors()
//{
//    return [
//        [
//            'class' => 'yii\filters\PageCache',
//            'only' => ['index'],
//            'duration' => 30,
//            'variations' => [
//                \Yii::$app->language,
//            ],
////            'dependency' => [
////                'class' => 'yii\caching\DbDependency',
////                'sql' => 'SELECT COUNT(*) FROM post',
////            ],
//        ],
//    ];
//}
    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        if (!empty($_SERVER['HTTP_CLIENT_IP'])) {
            $ip = $_SERVER['HTTP_CLIENT_IP'];
        } elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
            $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
        } else {
            $ip = $_SERVER['REMOTE_ADDR'];
        }
//        $readerCountry = new Reader('geo/GeoLite2-Country.mmdb');
//        $geo = $readerCountry->country($ip);
//        var_dump($geo->country->isoCode); //UA
//        var_dump($geo->country->names); //Ukraine
//        $readerCountry = new Reader('geo/GeoLite2-City.mmdb');
//        $geo = $readerCity->city($ip);
//        var_dump($geo->city->name); //Zhytomyr
  
        //$limit = Yii::$app->params['feedPostLimit'];
        if (!Yii::$app->user->isGuest){
            /* @var $currentUser User */
            $currentUser = Yii::$app->user->identity;
            
            // $myFeeds = Yii::$app->cache->get('cached_myFeeds');
           // if ($myFeeds === false) {
               // $myFeeds = $currentUser->getMyFeed($limit);
               // Yii::$app->cache->set('cached_myFeeds',$myFeeds , 30);
            //}
           
            
             $session = Yii::$app->session;
        $session->open();
        if ($session->has('stateFeeds')){
             $stateFeeds = $session->get('stateFeeds');
             $limitFeeds = $stateFeeds;
         }else{
             $session->set('stateFeeds', Yii::$app->params['feedsToShow']);
             $limitFeeds = $session->get('stateFeeds');
         }
                $myFeeds = $currentUser->getMyFeed($limitFeeds);
             
           
            ////////////////////////////////////должно запускаться при любой активности юзера
               //если пользователь существует в хэше, обновим его expire time
                Yii::$app->onLineUsers->writeTime($currentUser->id);
        }else{
            $myFeeds = NULL;
            $currentUser = NULL;
        }
        
       
        $session = Yii::$app->session;
        $session->open();
        if ($session->has('stateUsers')){
             $stateUsers = $session->get('stateUsers');
             $limitUsers = $stateUsers;
         }else{
             $session->set('stateUsers', Yii::$app->params['usersToShow']);
             $limitUsers = $session->get('stateUsers');
         }
        $users = User::getUsersWithLimit($limitUsers);
        
        return $this->render('index',[
            'users' => $users,
            'myFeeds' => $myFeeds,
            'limit' => $limitUsers,
            'currentUser' => $currentUser,
        ]);
    }
    
    
    public function actionAddUsers()
    {
          
        $limit = Yii::$app->params['feedPostLimit'];
        if (!Yii::$app->user->isGuest){
            /* @var $currentUser User */
            $currentUser = Yii::$app->user->identity;
            
//            $myFeeds = Yii::$app->cache->get('cached_myFeeds');
//            if ($myFeeds === false) {
//                $myFeeds = $currentUser->getMyFeed($limit);
//                Yii::$app->cache->set('cached_myFeeds',$myFeeds , 30);
//            }
            $session = Yii::$app->session;
        $session->open();
        if ($session->has('stateFeeds')){
             $stateFeeds = $session->get('stateFeeds');
             $limitFeeds = $stateFeeds;
         }else{
             $session->set('stateFeeds', Yii::$app->params['feedsToShow']);
             $limitFeeds = $session->get('stateFeeds');
         }
                $myFeeds = $currentUser->getMyFeed($limitFeeds);
           
        }else{
            $myFeeds = NULL;
            $currentUser = NULL;
        }
        
        $session = Yii::$app->session;
        $session->open();
        
        if ($session->has('stateUsers')){
             $stateUsers = $session->get('stateUsers');
             $stateUsers +=Yii::$app->params['usersToShow'];
             $session->set('stateUsers', $stateUsers);
             $limitUsers = $stateUsers;
         }else{
             $session->set('stateUsers', Yii::$app->params['usersToShow']);
             $limitUsers = $session->get('stateUsers');
         }
        
         $users = User::getUsersWithLimit($limitUsers);
        
        return $this->render('index',[
            'users' => $users,
            'myFeeds' => $myFeeds,
            'limit' => $limitUsers,
            'currentUser' => $currentUser,
        ]);
         
    }
    public function actionAddFeeds()
    {
          
        //$limit = Yii::$app->params['feedPostLimit'];
        if (!Yii::$app->user->isGuest){
            /* @var $currentUser User */
            $currentUser = Yii::$app->user->identity;
             
             $session = Yii::$app->session;
             $session->open();
             if ($session->has('stateFeeds')){
             $stateFeeds = $session->get('stateFeeds');
             $stateFeeds +=Yii::$app->params['feedsToShow'];
             $session->set('stateFeeds', $stateFeeds);
             $limitFeeds = $stateFeeds;
         }else{
             $session->set('stateFeeds', Yii::$app->params['feedsToShow']);
             $limitFeeds = $session->get('stateFeeds');
         }
                $myFeeds = $currentUser->getMyFeed($limitFeeds);
              
           
        }else{
            $myFeeds = NULL;
            $currentUser = NULL;
        }
      
        $session = Yii::$app->session;
        $session->open();
        if ($session->has('stateUsers')){
             $stateUsers = $session->get('stateUsers');
             $limitUsers = $stateUsers;
         }else{
             $session->set('stateUsers', Yii::$app->params['usersToShow']);
             $limitUsers = $session->get('stateUsers');
         }
        $users = User::getUsersWithLimit($limitUsers);
        
        
        
        return $this->render('index',[
            'users' => $users,
            'myFeeds' => $myFeeds,
            'limit' => $limitUsers,
            'currentUser' => $currentUser,
        ]);
         
    }
   public function actionSessionExperinent()
   {
      // Yii::$app->cache->flush();
       $number = Yii::$app->cache->get('cached_number');
       if ($number === false) {
       
        $number = self::generate();

        Yii::$app->cache->set('cached_number', $number, 30);
       }
   
       return $this->render('cache',[
            'number' => $number,
       ]);
      
   }
   public function actionAjaxTest()
   {
//      if (!empty($_FILES)) {
//            echo '<pre>';
//            print_r($_FILES);
//            echo '</pre>';die;
//        }
          //Yii::$app->response->format = Response::FORMAT_JSON;//теперь мы можем возвращать массив
        $model = new UploadedForm();

        if (Yii::$app->request->isPost) {
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if ($model->upload()) {
                // file is uploaded successfully
                return;
            }
        }

        return $this->render('ajax', ['model' => $model]);
//return [ 'success' => true,]

        
   }
   public function actionTest()
   {
         Yii::$app->response->format = Response::FORMAT_JSON;//теперь мы можем возвращать массив
         $limit = Yii::$app->params['feedPostLimit'];
        
            /* @var $currentUser User */
            $currentUser = Yii::$app->user->identity;
           
         
        
        $session = Yii::$app->session;
        $session->open();
        
        if ($session->has('stateUsers')){
             $stateUsers = $session->get('stateUsers');
             $stateUsers +=Yii::$app->params['usersToShow'];
             $session->set('stateUsers', $stateUsers);
             $limitUsers = $stateUsers;
         }else{
             $session->set('stateUsers', Yii::$app->params['usersToShow']);
             $limitUsers = $session->get('stateUsers');
         }
        
         $users = User::getUsersWithLimit($limitUsers);
         $isCurrentUser = User::isItCurrentUser($users); 
         $isUserOnline = User::isUserOnline($users); 
         $hrefForUserPage = User::hrefForUserPage($users); 
         
        return [         //это будет выглядеть вот так: {"success":true,"pictureUri":"/uploads/33/95/6d94b3c303573e2e9677cedfab68fd5626c7.jpg"}
                     'success' => true,
                     'users' => $users,
                     'isCurrentUser' => $isCurrentUser,
                     'isUserOnline' => $isUserOnline,
                     'hrefForUserPage' => $hrefForUserPage,

frontend/views/site/about.php
<?php
use Yii;
/* @var $this yii\web\View */
$this->title = 'About Imstagram';
?>
<div class="page-posts no-padding">
    <h1> <?= Yii::t('about', 'About Imstagram Project');  ?></h1>
    <p> Write text about the project!</p>
</div>

frontend/views/site/ajax.php
<?php
use yii\widgets\ActiveForm;

$this->title = 'AJAXTEST';
?>

<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

    <?= $form->field($model, 'imageFile')->fileInput() ?>

    <button>Submit</button>
<hr>
<?php ActiveForm::end() ?>


<form enctype='multipart/form-data' action="/ajaxtest" method="post" >
    <p class="target">
        <input type="hidden" name="_csrf-frontend" value="P5nqMZMnumLwTHAHs9iUd3o5FAIGgSbwGkk4S5ei5ARa3qABwWzrVsQtJWzWnd0xDGtcbna0a550enkc0uiraw==">
        <input type='file' name='filename[]'>
        <input type='button' value='+'>
        <input type='button' value='-'>
    </p>
    <h1 id="out1"></h1>
        
    <div>
        <input type='submit' value='Download'>
    </div> 
    <hr>
          
        
</form> 



frontend/views/site/cache.php
<?php
$this->title = 'Cache';


?>
<h1><?= $number; ?></h1>
   
 

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php
use yii\helpers\Url;
use frontend\modules\post\models\Post;
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use frontend\modules\post\models\Comment;
//use Yii;
/* @var $this yii\web\View */
/* @var $users[] frontend\models\User */
/* @var $currentUser frontend\models\User */
/* @var $myFeeds frontend\modules\post\models\User */

$this->title = 'My Yii Application';
?>

   
   <div class="site-index">

    <div class="body-content">

        <div class="row">
            <div class="col-lg-2">
                <h4>Explore users (<span id="ajaxtest"><?= count($users); ?></span>)</h4>
                <span class="bg-info">Active visitors: <strong><?php echo Yii::$app->onLineUsers->countGuests();?></strong></span>
                <div id="allusers">    
                 <?php foreach ($users as $user): ?>
                    <div class="post-meta" id="users"> 
                        <div class="post-title">
                            <img src="<?php echo $user->picture ? '/uploads/resized/' . $user->picture : '/default/default.jpg'; ?>" width="50" height="50" class="author-image" style="margin-right: 1px" />
                        
                       <div class="author-name">
                            <a class="<?= (Yii::$app->user->id == $user->id) ? 'bg-success' : ''; ?>"
                               href="<?= Url::to(['user/profile/view', 'nickname' => $user->getNickname()]); ?>"><?= $user->username; ?>
                            </a>
                           <?php if(Yii::$app->onLineUsers->isUserOnline($user->id)): ?>
                           <span class="bg-success">Online</span>
                            <?php else: ?>
                            <span class="bg-danger">Offline</span>
                           <?php endif; ?>
                        </div>
                        </div>
                    </div>
                <hr class="finish" style="margin-top: 1px; margin-bottom: 3px">

                <?php endforeach; ?>
               </div>

                <p><a class="btn btn-default center-block hidden" visib href="<?= Url::to(['site/add-users']); ?>">show more... &raquo;</a></p>
                <button type="button" id="load" class="btn btn-default center-block">show more... &raquo;</button>
            <div></div>
            </div>
            <div class="col-lg-8">
                
                                  
                       
                               
      
                <h2 class="text-center">My news feed (<?= count($myFeeds); ?>)</h2>
                              
                <?php if ($myFeeds): ?>
                    <?php foreach ($myFeeds as $oneFeed): ?>
                        <hr> 
                                              
                        
                        <a href="<?php echo Url::to(['/user/profile/view', 'nickname' => ($oneFeed['author_nickname']) ? $oneFeed['author_nickname'] : $oneFeed['author_id']]); ?>">
                                    <div class="col-md-12 bg-warning">
                                        <img src="<?php echo $oneFeed['author_picture']; ?>" width="40" height="40" class="img-circle" />
                                        <div class="author-name">

                                            <?php echo Html::encode($oneFeed['author_nickname']); ?>

                                        </div >   
                                        <?php echo " (" . Html::encode($oneFeed['author_name']) . ")"; ?>
                                    </div>
                        </a>
                               
                        <hr>
                        <p style="font-size:75%" class="text-right"><em><?php if ($oneFeed['post_created_at']) echo date('Y-m-d H:i', $oneFeed['post_created_at']); ?></em></p>
                        <?php echo $oneFeed['post_description']; ?>
                        <br>
                        <a href="<?php echo Url::to(['/post/comments/comment-form-view', 'postId' => $oneFeed['post_id']]); ?>">
                            <img src="/uploads/resized/<?php echo $oneFeed['post_filename']; ?>" id="profile-picture" style="max-width: 50%" class="center-block">
                        </a>
                        <hr>

                        <button type="button" class="btn btn-primary btn-xs btn-like <?php echo (('user-id:' . $currentUser->id) && (Post::isLiked($oneFeed['post_id'], $currentUser->id))) ? "display-none" : ""; ?>" data-id="<?php echo $oneFeed['post_id']; ?>">
                            <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
                            Like <span class="count-like badge"><?php echo Post::countLikes($oneFeed['post_id']); ?></span></button>

                        <button type="button" class="btn btn-primary btn-xs btn-dislike <?php echo (('user-id:' . $currentUser->id) && (Post::isLiked($oneFeed['post_id'], $currentUser->id))) ? "" : "display-none"; ?>" data-id="<?php echo $oneFeed['post_id']; ?>">
                            <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
                            Dislike <span class="count-dislike badge"><?php echo Post::countLikes($oneFeed['post_id']); ?></span></button>

                        <a class="btn btn-default btn-xs" href="<?php echo Url::to(['/post/comments/comment-form-view', 'postId' => $oneFeed['post_id']]); ?>" role="button">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            Comments...<span class="count-dislike badge"><?php echo Comment::countComments($oneFeed['post_id']); ?></span></a>
                    <?php endforeach; ?>
                   <p><a class="btn btn-default center-block" href="<?= Url::to(['site/add-feeds']); ?>">show more... &raquo;</a></p>
                        <?php else: ?>
                    <h4 class="text-center bg-info">You have no news feed. You should subscribe for more people to have one.</h4>
                    
                <?php endif; ?>
              
            </div>
            <div class="col-lg-8">
               
            </div>
        </div>

    </div>
</div>